### ISSUE TITLE
Turn static methods into members of another class?

### ISSUE THREAD

**Issue by RubenVerborgh** [rubensworks/jsonld-context-parser.js#10]
I find it a bit strange that `ContextParser` has a lot of static methods that do not have anything to do with parsing.

Perhaps the `parse` method should return a `Context` instance with member methods?
This instance could then have a `normalizedContext` property with the current return value.

**Comment by rubensworks** [comment]
I definitely see the advantage of that, mainly because the methods would be safer, as you wouldn't be able to call the static methods on a non-normalized context in a non-TS codebase.

The reasoning behind the current architecture is that the normalized context is still a valid JSON-LD context, so it can directly be used instead of the original context. Also, straightforward caching of the normalized output, as it's a POJO.
Furthermore, all operations after normalizing are fully stateless, which is why I find static methods to be a good fit.

I don't see an urgent need to change this right now, perhaps I'll change my mind in the future.

**Comment by RubenVerborgh** [comment]
Makes sense; something else to consider is putting the static methods on a different object (as they are independent of the parser).

**Comment by rubensworks** [comment]
This has been done in https://github.com/rubensworks/jsonld-context-parser.js/tree/feature/spec-1.1.
This will be a breaking change obviously.

**Comment by rubensworks** [comment]
Released in 2.0.0.
